user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

menu:
    resource: "@MenuBaseBundle/Controller/"
    type: annotation
    prefix: /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"